servicestarfish/services/models.py
# Imports

from __future__ import unicode_literals
from django.conf import settings
from django.contrib.auth.models import Group
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import models
from django.utils.translation import ugettext_lazy as _
from modelcluster.contrib.taggit import ClusterTaggableManager
from modelcluster.fields import ParentalKey
from taggit.models import TaggedItemBase
from wagtail.wagtailadmin.edit_handlers import InlinePanel, FieldPanel, MultiFieldPanel, PageChooserPanel
from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailcore.models import Page, Orderable
from wagtail.wagtailsearch import index
from wagtailmodelchooser.edit_handlers import register_chooser_for_model
from lemurlink.models import RelatedLinkModel
from taxonomytiger.models import StringLookupModel
from servicestarfish.technologies.models import Product, ProductChooserPanel
from servicestarfish.menus.models import Request, RequestChooserPanel

GroupChooserPanel = register_chooser_for_model(Group, title_field="name")

# Exports

__all__ = (
)

# Constants

AUTH_USER_MODEL = settings.AUTH_USER_MODEL

# Lookups


class Category(StringLookupModel):
    """A service category. Typically, a line of service."""

    class Meta:
        ordering = ["label"]
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

CategoryChooserPanel = register_chooser_for_model(Category)


class Lifecycle(StringLookupModel):
    """A lifecycle represents a phase or stage in which a service may be described."""

    sort_order = models.PositiveSmallIntegerField(
        _("sort oder"),
        help_text=_("Order in which the lifecycle should appear.")
    )

    panels = StringLookupModel.panels + [
        FieldPanel("sort_order"),
    ]

    class Meta:
        ordering = ["sort_order"]
        verbose_name = _("Lifecycle")
        verbose_name_plural = _("Lifecycles")

LifecycleChooserPanel = register_chooser_for_model(Lifecycle)

# Models


class ServiceIndexPage(Page):
    """An index page for services. One might treat this like a service catalog."""

    intro = RichTextField(
        _("intro"),
        blank=True,
        help_text=_("Brief introduction appearing before the package list."),
        null=True
    )

    is_catalog = models.NullBooleanField(
        _("catalog"),
        help_text=_("Indicates this page represents a service catalog.")
    )

    content_panels = Page.content_panels + [
        FieldPanel("intro", classname="full"),
        FieldPanel("is_catalog"),
    ]

    search_fields = Page.search_fields + [
        index.SearchField("intro"),
    ]

    subpage_types = [
        "ServiceIndexPage",
        "ServicePage",
    ]

    def get_subpages(self, criteria=None):
        """Get a list of packages."""
        qs = ServicePage.objects.live().descendant_of(self)

        if isinstance(criteria, dict):
            qs = qs.filter(**criteria)

        return qs

    def get_categories(self):
        a = list()

        qs = Category.objects.all()
        for category in qs:
            services = ServicePage.objects.live().descendant_of(self).filter(category=category)
            a.append((category, services))

        return a

    def get_context(self, request, *args, **kwargs):
        context = super(ServiceIndexPage, self).get_context(request, *args, **kwargs)

        if self.is_catalog:
            context['categories'] = None
            objects = ServiceIndexPage.objects.live().descendant_of(self)
        else:
            context['categories'] = self.get_categories()

            # Get the objects.
            objects = self.get_subpages()

        # Pagination
        page = request.GET.get('page')
        entries_per_page = 9
        paginator = Paginator(objects, entries_per_page)
        try:
            objects = paginator.page(page)
        except PageNotAnInteger:
            objects = paginator.page(1)
        except EmptyPage:
            objects = paginator.page(paginator.num_pages)

        # Update template context
        context['active_page'] = "services"
        context['subpages'] = objects

        return context

    @property
    def subpages(self):
        return self.get_subpages()


class ServicePageAgreement(RelatedLinkModel, Orderable):
    """Associate an SLA or OLA with a service."""

    covers_customer = models.NullBooleanField(
        _("customer"),
        help_text=_("Indicates this agreement is with a specific customer.")
    )

    covers_organization = models.NullBooleanField(
        _("organization"),
        help_text=_("Indicates this agreement is with the whole organization.")
    )

    covers_service = models.NullBooleanField(
        _("service"),
        help_text=_("Indicates this agreement is specific to the selected service.")
    )

    is_multi_level = models.NullBooleanField(
        _("multi-level"),
        help_text=_("Indicates this is a multi-level agreement.")
    )

    page = ParentalKey("ServicePage", related_name="agreements")

    CONTRACT = "contract"
    OLA = "OLA"
    SLA = "SLA"
    TYPE_CHOICES = (
        (OLA, _("Operating Level Agreement")),
        (SLA, _("Service Level Agreement")),
        (CONTRACT, _("Underpinning Contract")),
    )
    type = models.CharField(
        _("type"),
        choices=TYPE_CHOICES,
        default=SLA,
        help_text=_("Select the type of agreement."),
        max_length=32
    )

    panels = RelatedLinkModel.panels + [
        FieldPanel("type"),
        MultiFieldPanel(
            [
                FieldPanel("covers_organization"),
                FieldPanel("covers_customer"),
                FieldPanel("covers_service"),
            ],
            heading=_("Scope")
        )
    ]

    class Meta:
        verbose_name = _("Service Agreement")
        verbose_name_plural = _("Service Agreements")

    def save(self, *args, **kwargs):
        a = list()
        if self.covers_customer:
            a.append(1)

        if self.covers_organization:
            a.append(1)

        if self.covers_service:
            a.append(1)

        if sum(a) >= 2:
            self.is_multi_level = True
        else:
            self.is_multi_level = False

        super(ServicePageAgreement, self).save(*args, **kwargs)


class ServicePageProduct(Orderable):
    """Connect products with services."""

    is_primary = models.NullBooleanField(
        _("primary"),
        help_text=_("Indicates this is the primary product for the service.")
    )

    # Products are connected to the business (or other) service from the ServicePage.
    page = ParentalKey("ServicePage", related_name="products")

    product = models.ForeignKey(
        Product,
        help_text=_("Select the product."),
        on_delete=models.PROTECT,
        related_name="services",
        verbose_name=_("product")
    )

    panels = [
        ProductChooserPanel("product"),
        FieldPanel("is_primary"),
    ]

    @property
    def description(self):
        return self.product.description

    @property
    def service(self):
        return self.page

    @property
    def title(self):
        return self.product.title

    @property
    def vendor(self):
        return self.product.vendor


class ServicePageRequest(Orderable):
    """Connect requests with services."""

    # Request is connected to the business (or other) service from the ServicePage.
    page = ParentalKey("ServicePage", related_name="requests")

    request = models.ForeignKey(
        Request,
        help_text=_("Select the request"),
        related_name="services",
        verbose_name=_("request")
    )

    panels = [
        RequestChooserPanel("request"),
    ]

    def __unicode__(self):
        return u"%s" % self.request.title

    @property
    def description(self):
        return self.request.description

    @property
    def grouping(self):
        return self.request.grouping

    @property
    def service(self):
        return self.page

    @property
    def show_in_all_groups(self):
        return self.request.show_in_all_groups

    @property
    def title(self):
        return self.request.title


class ServicePageTag(TaggedItemBase):
    """Associate tags with a service."""

    content_object = ParentalKey("ServicePage", related_name="tagged_items")


class SupportingService(Orderable):
    """Link a service to it's supporting services."""

    # TODO: Remove SupportingService.link_external since it can't really be used.

    # TODO: Rename link_page to supporting and page to dependent?

    # TODO: Remove properties and methods created to alias the supporting service.

    # OLA (document, link, or page)

    link_external = models.URLField(
        _("External Link"),
        blank=True,
        help_text=_("Enter the full URL if the service is not maintained in this tool."),
        max_length=1024,
        null=True,
    )

    link_page = models.ForeignKey(
        "ServicePage",
        null=True,
        blank=True,
        help_text=_("Link to another service maintained in this tool."),
        related_name='dependent_services',
        verbose_name=_("Link to Service")
    )

    page = ParentalKey("ServicePage", related_name="supporting_services")

    panels = [
        FieldPanel('link_external'),
        PageChooserPanel('link_page'),
    ]

    class Meta:
        ordering = ["sort_order"]
        verbose_name = _("Supporting Service")
        verbose_name_plural = _("Supporting Services")

    @property
    def assignment(self):
        return self.supporting_service.assignment

    @property
    def category(self):
        return self.supporting_service.category

    def get_link(self):
        """Get the actual URL from the local page or external link (in that order).

        :rtype: str

        """
        if self.link_page:
            return self.link_page.url
        else:
            return self.link_external

servicestarfish/services/templates/servicestarfish_services/service_index_page.html
{% extends "base.html" %}
{% load i18n %}
{% load wagtailcore_tags %}

{% block title %}
    {% trans "Services" %}
{% endblock %}

{% block page_header %}
    {% trans "Index" as subtitle_x %}
    {% with title=page.title subtitle=subtitle_x %}
        {% include "includes/page_header.html" %}
    {% endwith %}
{% endblock %}

{% block content %}

    {% if page.is_catalog %}
        <ul>
            {% for subpage in subpages %}
                <li><a href="{% pageurl subpage %}">{{ subpage }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        {% for category, services in categories %}
            <ul>
                <li>
                    {{ category }}
                    {% if services.count > 0 %}
                        <ul>
                            {% for service in services %}
                                <li>
                                    <a href="{% pageurl service %}">{{ service }}</a>
                                    {% if service.has_requests %}
                                        <ul>
                                            {% for request in service.menu_items %}
                                                <li>
                                                    {{ request }}
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            </ul>
        {% endfor %}
    {% endif %}

{% endblock %}

{% block sidebar %}
{% endblock %}

servicestarfish/services/templates/servicestarfish_services/service_page.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Service" %} - {{ service.title }}
{% endblock %}

{% block page_header %}
    {% trans "Service" as subtitle_x %}
    {% with title=service.title subtitle=subtitle_x %}
        {% include "includes/page_header.html" %}
    {% endwith %}
{% endblock %}

{% block content %}

    <div class="well">
        <b>{% trans "Type" %}</b> {{ service.get_type_display }} &bull;
        <b>{% trans "Category" %}</b> {{ service.category }} &bull;
        <b>{% trans "Priority" %}</b> {{ service.get_priority_display }} &bull;
    </div>

    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#overview" aria-controls="overview" role="tab" data-toggle="tab">{% trans "Overview" %}</a></li>
        <li role="presentation"><a href="#relationships" aria-controls="relationships" role="tab" data-toggle="tab">{% trans "Relationships" %}</a></li>
        <li role="presentation"><a href="#menu" aria-controls="menu" role="tab" data-toggle="tab">{% trans "Menu" %}</a></li>
        <li role="presentation"><a href="#administration" aria-controls="administration" role="tab" data-toggle="tab">{% trans "Administration" %}</a></li>
  </ul>

    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="overview">
            <h2>{% trans "Overview" %}</h2>
            {% if service.description %}
                <p>{{ service.description|linebreaksbr }}</p>
            {% else %}
                <p>{% trans "No description has been provided for this service." %}</p>
            {% endif %}
        </div>
        <div role="tabpanel" class="tab-pane" id="relationships">
            <h2>{% trans "Relationships" %}</h2>

            <h3>{% trans "Products" %}</h3>
            {% if service.has_products %}
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>{% trans "Title" %}</th>
                            <th>{% trans "Description" %}</th>
                            <th>{% trans "Vendor" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in service.products.all %}
                        <tr>
                            <td>{{ product.title }}</td>
                            <td>{{ product.description}}</td>
                            <td>{{ product.vendor }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>
                    {% trans "No products have been associated with this service." %}
                </p>
            {% endif %}

            <h3>{% trans "Supporting Services" %}</h3>
            {% if service.has_supporting %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>{% trans "Title" %}</th>
                            <th>{% trans "Type" %}</th>
                            <th>{% trans "Category" %}</th>
                            <th>{% trans "Purpose" %}</th>
                            <th>{% trans "Scope" %}</th>
                            <th>{% trans "Assigned To" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for supporting in service.get_supporting %}
                        <tr>
                            <td>{{ supporting.title }}</td>
                            <td>{{ supporting.get_type_display }}</td>
                            <td>{{ supporting.category }}</td>
                            <td>{{ supporting.get_purpose_display }}</td>
                            <td>{{ supporting.get_scope_display }}</td>
                            <td>{{ supporting.assignment }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p><i>{{ service.title }}</i> {% trans "does not depend on any other service." %}</p>
            {% endif %}

            <h3>{% trans "Dependent Services" %}</h3>
            {% if service.has_dependents %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>{% trans "Title" %}</th>
                            <th>{% trans "Type" %}</th>
                            <th>{% trans "Category" %}</th>
                            <th>{% trans "Purpose" %}</th>
                            <th>{% trans "Scope" %}</th>
                            <th>{% trans "Assigned To" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for dependent in service.get_dependents %}
                        <tr>
                            <td>{{ dependent.title }}</td>
                            <td>{{ dependent.get_type_display }}</td>
                            <td>{{ dependent.category }}</td>
                            <td>{{ dependent.get_purpose_display }}</td>
                            <td>{{ dependent.get_scope_display }}</td>
                            <td>{{ dependent.assignment }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>{% trans "No services depend on" %} <i>{{ service.title }}</i></p>
            {% endif %}
        </div>
        <div role="tabpanel" class="tab-pane" id="menu">
             <h2>{% trans "Requests" %}</h2>
            {% if service.has_requests %}

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>{% trans "Grouping" %}</th>
                            <th>{% trans "Title" %}</th>
                            <th>{% trans "Description" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for request in service.menu_items %}
                        <tr>
                            <td>
                                {% if request.show_in_all_groups %}
                                    {% trans "(Commonly Available)" %}
                                {% else %}
                                    {{ request.grouping }}
                                {% endif %}
                            </td>
                            <td>{{ request.title}}</td>
                            <td>{{ request.description}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>
                    {% trans "No menu items have been associated with this service." %}
                </p>
            {% endif %}
        </div>
        <div role="tabpanel" class="tab-pane" id="administration">
            <h2>{% trans "Administration" %}</h2>
            <table class="table">
                <tbody>
                    <tr>
                        <th>{% trans "Budget" %}</th>
                        <td>{{ service.budget }}</td>
                    </tr>
                    <tr>
                        <th>{% trans "Last Review" %}</th>
                        <td>{{ service.last_review_dt }}</td>
                    </tr>
                    <tr>
                        <th>{% trans "Next Review" %}</th>
                        <td>{{ service.next_review_dt }}</td>
                    </tr>
                    <tr>
                        <th>{% trans "Stage" %}</th>
                        {% trans "Not Specific" as no_lifecycle_x %}
                        <td>{{ service.lifecycle|default_if_none:no_lifecycle_x }}</td>
                    </tr>
                    <tr>
                        <th>{% trans "Status" %}</th>
                        <td>{{ service.get_portfolio_display }}</td>
                    </tr>
                </tbody>
            </table>

            {% if service.has_agreements %}
                <h3>{% trans "Agreements" %}</h3>
                {% trans "No Title Available" as no_title_x %}
                <ul>
                    {% for agreement in service.agreements.all %}
                        <li>
                            <a href="{{ agreement.link }}">{{ agreement.title|default_if_none:no_title_x }}</a>
                        </li>
                    {% endfor %}

                </ul>
            {% endif %}

        </div>
  </div>

{% endblock %}

{% block sidebar %}
    <table class="table">
        <tbody>
            <tr>
                <th>{% trans "Title" %}</th>
                <td>{{ service.title }}</td>
            </tr>
            <tr>
                <th>{% trans "Type" %}</th>
                <td>{{ service.get_type_display}}</td>
            </tr>
            <tr>
                <th>{% trans "Category" %}</th>
                <td>{{ service.category }}</td>
            </tr>
            <tr>
                <th>{% trans "Scope" %}</th>
                <td>{{ service.get_scope_display}}</td>
            </tr>
            <tr>
                <th>{% trans "Purpose" %}</th>
                <td>{{ service.get_purpose_display}}</td>
            </tr>
            <tr>
                <th>{% trans "Priority" %}</th>
                <td>{{ service.get_priority_display }}</td>
            </tr>
            <tr>
                <th>{% trans "Assigned To" %}</th>
                <td>{{ service.assignment }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}